insert into category (name) values ('Site Furnishings');
insert into category (name) values ('Glass & Glazing');
insert into category (name) values ('Structural and Misc Steel (Fabrication)');
insert into category (name) values ('RF Shielding');
insert into category (name) values ('Electrical');
insert into category (name) values ('Landscaping & Irrigation');
insert into category (name) values ('Ornamental Railings');
insert into category (name) values ('Structural & Misc Steel Erection');
insert into category (name) values ('Glass & Glazing');
insert into category (name) values ('Waterproofing & Caulking');
insert into category (name) values ('Construction Clean and Final Clean');
insert into category (name) values ('Roofing (Metal)');
insert into category (name) values ('Marlite Panels (FED)');
insert into category (name) values ('Sitework & Site Utilities');
insert into category (name) values ('Overhead Doors');
insert into category (name) values ('Framing (Wood)');
insert into category (name) values ('Electrical and Fire Alarm');
insert into category (name) values ('Wall Protection');
insert into category (name) values ('Waterproofing & Caulking');
insert into category (name) values ('Fire Sprinkler System');
insert into category (name) values ('Ornamental Railings');
insert into category (name) values ('Masonry');
insert into category (name) values ('Wall Protection');
insert into category (name) values ('Drywall & Acoustical (FED)');
insert into category (name) values ('HVAC');
insert into category (name) values ('Prefabricated Aluminum Metal Canopies');
insert into category (name) values ('Granite Surfaces');
insert into category (name) values ('Exterior Signage');
insert into category (name) values ('RF Shielding');
insert into category (name) values ('Roofing (Metal)');
insert into category (name) values ('Plumbing & Medical Gas');
insert into category (name) values ('Masonry');
insert into category (name) values ('Plumbing & Medical Gas');
insert into category (name) values ('Site Furnishings');
insert into category (name) values ('Framing (Wood)');
insert into category (name) values ('Framing (Steel)');
insert into category (name) values ('Hard Tile & Stone');
insert into category (name) values ('Glass & Glazing');
insert into category (name) values ('Doors, Frames & Hardware');
insert into category (name) values ('Prefabricated Aluminum Metal Canopies');
insert into category (name) values ('Drilled Shafts');
insert into category (name) values ('Rebar & Wire Mesh Install');
insert into category (name) values ('Drywall & Acoustical (MOB)');
insert into category (name) values ('Site Furnishings');
insert into category (name) values ('Roofing (Metal)');
insert into category (name) values ('Overhead Doors');
insert into category (name) values ('Epoxy Flooring');
insert into category (name) values ('Drilled Shafts');
insert into category (name) values ('Framing (Steel)');
insert into category (name) values ('Masonry & Precast');
insert into category (name) values ('Elevator');
insert into category (name) values ('Hard Tile & Stone');
insert into category (name) values ('Electrical and Fire Alarm');
insert into category (name) values ('Retaining Wall and Brick Pavers');
insert into category (name) values ('Plumbing & Medical Gas');
insert into category (name) values ('RF Shielding');
insert into category (name) values ('Structural and Misc Steel (Fabrication)');
insert into category (name) values ('Sitework & Site Utilities');
insert into category (name) values ('Framing (Wood)');
insert into category (name) values ('Landscaping & Irrigation');
insert into category (name) values ('RF Shielding');
insert into category (name) values ('HVAC');
insert into category (name) values ('Soft Flooring and Base');
insert into category (name) values ('Elevator');
insert into category (name) values ('Electrical');
insert into category (name) values ('Drywall & Acoustical (FED)');
insert into category (name) values ('Drywall & Acoustical (FED)');
insert into category (name) values ('Roofing (Asphalt)');
insert into category (name) values ('Doors, Frames & Hardware');
insert into category (name) values ('Framing (Steel)');
insert into category (name) values ('Hard Tile & Stone');
insert into category (name) values ('Masonry & Precast');
insert into category (name) values ('Masonry & Precast');
insert into category (name) values ('EIFS');
insert into category (name) values ('Electrical');
insert into category (name) values ('Structural & Misc Steel Erection');
insert into category (name) values ('Granite Surfaces');
insert into category (name) values ('Marlite Panels (FED)');
insert into category (name) values ('Epoxy Flooring');
insert into category (name) values ('Drilled Shafts');
insert into category (name) values ('Glass & Glazing');
insert into category (name) values ('Structural & Misc Steel Erection');
insert into category (name) values ('Termite Control');
insert into category (name) values ('Structural and Misc Steel (Fabrication)');
insert into category (name) values ('Glass & Glazing');
insert into category (name) values ('Glass & Glazing');
insert into category (name) values ('Hard Tile & Stone');
insert into category (name) values ('Construction Clean and Final Clean');
insert into category (name) values ('Marlite Panels (FED)');
insert into category (name) values ('Masonry');
insert into category (name) values ('Electrical and Fire Alarm');
insert into category (name) values ('Construction Clean and Final Clean');
insert into category (name) values ('Drilled Shafts');
insert into category (name) values ('Electrical and Fire Alarm');
insert into category (name) values ('Termite Control');
insert into category (name) values ('Casework');
insert into category (name) values ('HVAC');
insert into category (name) values ('Masonry');
insert into category (name) values ('Waterproofing & Caulking');
insert into category (name) values ('Casework');
